KeVin
#1932

Brian — 11/06/2022 5:39 PM
First(R) = {d,g}

First(T) = {g}
Brian — 11/14/2022 1:06 PM
alo
check check
do u copy?
Alo
LatLataLatLataLatLataLLatLataLatLataLLatLataLatLataLatLataLLatLataLatLataLatLataLLatLataLatLataLLatLataLatLataLatLataLLatLataLatLataLLatLataLatLataLaaLLatLataLLaaLLL
Lát ao aoaaoaaoaaaoaaoaaaoaaoaaoaaaaoaaoaaoaaaoaaoaaaaoaaoaaoaaaoaaoaaaoaaoaaoaaaaaoaaoaaoaaaoaaoaaaoaaoaaoaaaaoaaoaaoaaaoaaoaaaaaa
AI chan ai le day Kevin
KeVin — 11/14/2022 1:08 PM
sao ko nghe
Brian — 11/14/2022 1:08 PM
nghe gi?
k nghe chat a
a nghe ma
KeVin — 11/14/2022 1:08 PM
uh
chan hay le
Brian — 11/14/2022 1:10 PM
a le nhu cu nha
e chan di
KeVin — 11/14/2022 1:32 PM
Attachment file type: acrobat
Quiz_Quiz_8.pdf
93.29 KB
cau 10 kho vl
Brian — 11/14/2022 1:33 PM
Attachment file type: document
Quiz8-7.pages
101.04 KB
Attachment file type: acrobat
Quiz__8.pdf
213.83 KB
KeVin — 11/14/2022 1:52 PM
san a gui may cai file viet di
Brian — 11/14/2022 1:52 PM
1 file viet cau 7 gui roi do
dang coi cau 5
KeVin — 11/14/2022 1:55 PM
cau do file mo ko dc
Brian — 11/14/2022 1:56 PM
fibonacci_dynamic(n)

{

    A is an array of size 3.

    A[0] = 0

    A[1] = 1

    print A[0],A[1]

        for i = 2 to n:

            A[2] = A[0] + A[1]

            print A[2]

            A[0] = A[1]

            A[1] = A[0]

        endfor

}
Cau 5
Image
KeVin — 11/14/2022 2:01 PM
cau 5 la hinh hay chu v
Brian — 11/14/2022 2:02 PM
hinhf
chu la cau 7
KeVin — 11/14/2022 2:02 PM
uh
Brian — 11/14/2022 2:04 PM
cau 10 xong chua
KeVin — 11/14/2022 2:06 PM
gui mess
moi lam dc pseudo code
Brian — 11/14/2022 2:06 PM
ok
cai cau 5
a dang xem lai
KeVin — 11/14/2022 2:06 PM
master theorem gi chua lam dc
KeVin — 11/14/2022 2:16 PM
xong chua
e nop bai
Brian — 11/14/2022 2:16 PM
uk thooi nop bai
KeVin — 11/14/2022 2:17 PM
wtf
Brian — 11/14/2022 2:17 PM
dkm
sai nhieu the
KeVin — 12/04/2022 8:48 PM
https://drive.google.com/file/d/1GUOrfFueeDhcm44qhwTSVMzH0Fsi9DZr/view?usp=share_link
Google Drive: Sign-in
Access Google Drive with a Google account (for personal use) or Google Workspace account (for business use).
https://drive.google.com/file/d/1GUOrfFueeDhcm44qhwTSVMzH0Fsi9DZr/view?usp=share_link
Google Drive: Sign-in
Access Google Drive with a Google account (for personal use) or Google Workspace account (for business use).
https://drive.google.com/file/d/10uqhn4cGhz0pvUPqRV2RZL-G_a_f_8KB/view?usp=share_link
Google Docs
2022-11-28 13-03-35.mkv
https://drive.google.com/file/d/1GUOrfFueeDhcm44qhwTSVMzH0Fsi9DZr/view?usp=share_link
Google Drive: Sign-in
Access Google Drive with a Google account (for personal use) or Google Workspace account (for business use).
KeVin — 12/04/2022 9:46 PM
https://drive.google.com/file/d/1PKKf-sH-SanI3uPW8tlPwDk1PvM9IUuR/view?usp=share_link
Google Docs
2022-11-14 17-36-09.mkv
Brian — 12/04/2022 10:36 PM
https://www.youtube.com/watch?v=QoOALbef3ZM&ab_channel=AnitaR
YouTube
Anita R
Compiler Design: Predictive Parsing-LL(1)
Image
KeVin — Today at 7:24 PM
import React, { useState } from "react";
import { Transition } from "@headlessui/react";
import Head from 'next/head'
import {FaLinkedin, FaGoogle, FaGithub, FaBars} from 'react-icons/fa';
import Image from 'next/image';
import bookstore from '../public/bookstore.jpg'
import kevin from '../public/kevin.png'
import brian from '../public/brian.png'
import dharmesh from '../public/dharmesh.png'
import tuan from '../public/tuan.png'

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div>

      <Head>
        <title>BookDeal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/shopping-bag1.png" />
      </Head>

      <nav className="bg-gray-800 mb-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center">
              <div className="flex-shrink-0">
                <img
                  src='shopping-bag0.png'
                  alt="Icon"
                  className="h-10 w-10"
                />
              </div>
              <a className="text-white px-3 py-2 font-burtons text-3xl mt-3">BookDeal</a>
              <div className="hidden md:block">
                <div className="ml-10 flex items-baseline space-x-4">

                  <a
                    href="/"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Home
                  </a>

                  <a
                    href="products"
                    className=" hover:bg-gray-700 text-gray-400 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Products
                  </a>

                  <a
                    href="contact"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Contact
                  </a>

                  <a
                    href="about"
                    className="bg-gray-700 text-white px-3 py-2 rounded-md text-sm font-medium cursor-default"
                  >
                    About
                  </a>

                  <a
                    href="#"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Login
                  </a>
                </div>
              </div>
            </div>
            <div className="-mr-2 flex md:hidden">
              <button
                onClick={() => setIsOpen(!isOpen)}
                type="button"
                className="bg-gray-900 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                aria-controls="mobile-menu"
                aria-expanded="false"
              >
                <span className="sr-only">Open main menu</span>
                {!isOpen ? (
                  <svg
                    className="block h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16"
                    />
                  </svg>
                ) : (
... (141 lines left)
Collapse
about.js
13 KB
﻿
import React, { useState } from "react";
import { Transition } from "@headlessui/react";
import Head from 'next/head'
import {FaLinkedin, FaGoogle, FaGithub, FaBars} from 'react-icons/fa';
import Image from 'next/image';
import bookstore from '../public/bookstore.jpg'
import kevin from '../public/kevin.png'
import brian from '../public/brian.png'
import dharmesh from '../public/dharmesh.png'
import tuan from '../public/tuan.png'

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div>

      <Head>
        <title>BookDeal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/shopping-bag1.png" />
      </Head>

      <nav className="bg-gray-800 mb-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center">
              <div className="flex-shrink-0">
                <img
                  src='shopping-bag0.png'
                  alt="Icon"
                  className="h-10 w-10"
                />
              </div>
              <a className="text-white px-3 py-2 font-burtons text-3xl mt-3">BookDeal</a>
              <div className="hidden md:block">
                <div className="ml-10 flex items-baseline space-x-4">

                  <a
                    href="/"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Home
                  </a>

                  <a
                    href="products"
                    className=" hover:bg-gray-700 text-gray-400 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Products
                  </a>

                  <a
                    href="contact"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Contact
                  </a>

                  <a
                    href="about"
                    className="bg-gray-700 text-white px-3 py-2 rounded-md text-sm font-medium cursor-default"
                  >
                    About
                  </a>

                  <a
                    href="#"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Login
                  </a>
                </div>
              </div>
            </div>
            <div className="-mr-2 flex md:hidden">
              <button
                onClick={() => setIsOpen(!isOpen)}
                type="button"
                className="bg-gray-900 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                aria-controls="mobile-menu"
                aria-expanded="false"
              >
                <span className="sr-only">Open main menu</span>
                {!isOpen ? (
                  <svg
                    className="block h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16"
                    />
                  </svg>
                ) : (
                  <svg
                    className="block h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </svg>
                )}
              </button>
            </div>
          </div>
        </div>

        <Transition
          show={isOpen}
          enter="transition ease-out duration-100 transform"
          enterFrom="opacity-0 scale-95"
          enterTo="opacity-100 scale-100"
          leave="transition ease-in duration-75 transform"
          leaveFrom="opacity-100 scale-100"
          leaveTo="opacity-0 scale-95"
        >
          {(ref) => (
            <div className="md:hidden" id="mobile-menu">
              <div ref={ref} className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                <a
                  href="/"
                  className="hover:bg-gray-700 text-gray-400 block px-3 py-2 rounded-md text-base font-medium"
                >
                  Home
                </a>

                <a
                  href="products"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Products
                </a>

                <a
                  href="contact"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Contact
                </a>

                <a
                  href="#"
                  className="bg-gray-700 text-white block px-3 py-2 rounded-md text-base font-medium cursor-default"
                >
                  About
                </a>

                <a
                  href="#"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Login
                </a>
              </div>
            </div>
          )}
        </Transition>
      </nav>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <div className=' text-center p-10'>
            <h2 className='text-5xl py-2 text-orange-500 font-medium'>About Us</h2>
            <h3 className=' text-2xl py-2'>Developer and designer</h3>
            <p className=' text-sm py-5 leading-8'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <FaGoogle/>
            <FaLinkedin/>
            <FaGithub/>
          </div>
          <div className='relative w-4/5 h-96 my-20 mx-auto overflow-hidden'>
            <Image src={bookstore} layout='fill' objectFit='cover'/>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-center text-3xl py-1">Services We Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
          <div className="md:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={kevin} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Kevin Nguyen</h3>
              <p className="py-2">Front-end web developer and designer</p>
              <h4 className="py-4 text-orange-600">My Duty</h4>
              <p className="text-gray-800 py-1">I develop and design the look of the webpage. My goal is to make it reactive and clean looking with some of the modern feel. The most challenging part of my website is the navigation bar and its functionality. Because this is still my new language, parts of this website could be buggy or broken.</p>
              <h4 className=" py-4 text-orange-600">Tools I used</h4>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={brian} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Brian Nguyen</h3>
              <p className="py-2">Front-end web developer and designer</p>
              <h4 className="py-4 text-teal-600">My Work</h4>
              <p className="text-gray-800 py-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={dharmesh} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Dharmesh Tewari</h3>
              <p className="py-2">Back-end developer</p>
              <h4 className="py-4 text-teal-600">My Work</h4>
              <p className="text-gray-800 py-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={tuan} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Tuan Nguyen</h3>
              <p className="py-2">Scrum master</p>
              <h4 className="py-4 text-teal-600">My Work</h4>
              <p className="text-gray-800 py-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
      </main>

    </div>
  )
}