import React, { useState } from "react";
import { Transition } from "@headlessui/react";
import Head from 'next/head'
import {FaLinkedin, FaGoogle, FaGithub, FaBars} from 'react-icons/fa';
import Image from 'next/image';
import creditCards from '../public/credit-cards.svg'
import offline from '../public/offline.png'
import openBook from '../public/open_book.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div>

      <Head>
        <title>BookDeal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/shopping-bag1.png" />
      </Head>

      <nav className="bg-gray-800 mb-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center">
              <div className="flex-shrink-0">
                <img
                  src='shopping-bag0.png'
                  alt="Icon"
                  className="h-10 w-10"
                />
              </div>
              <a className="text-white px-3 py-2 font-burtons text-3xl mt-3">BookDeal</a>
              <div className="hidden md:block">
                <div className="ml-10 flex items-baseline space-x-4">
                  <a
                    href="#"
                    className=" bg-gray-700 text-white px-3 py-2 rounded-md text-sm font-medium cursor-default"
                  >
                    Home
                  </a>

                  <a
                    href="products"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Products
                  </a>

                  <a
                    href="contact"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Contact
                  </a>

                  <a
                    href="about"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    About
                  </a>

                  <a
                    href="#"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Login
                  </a>
                </div>
              </div>
            </div>
            <div className="-mr-2 flex md:hidden">
              <button
                onClick={() => setIsOpen(!isOpen)}
                type="button"
                className="bg-gray-900 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                aria-controls="mobile-menu"
                aria-expanded="false"
              >
                <span className="sr-only">Open main menu</span>
                {!isOpen ? (
                  <svg
                    className="block h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16"
                    />
                  </svg>
                ) : (
                  <svg
                    className="block h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </svg>
                )}
              </button>
            </div>
          </div>
        </div>

        <Transition
          show={isOpen}
          enter="transition ease-out duration-100 transform"
          enterFrom="opacity-0 scale-95"
          enterTo="opacity-100 scale-100"
          leave="transition ease-in duration-75 transform"
          leaveFrom="opacity-100 scale-100"
          leaveTo="opacity-0 scale-95"
        >
          {(ref) => (
            <div className="md:hidden" id="mobile-menu">
              <div ref={ref} className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                <a
                  href="#"
                  className="bg-gray-700 text-white block px-3 py-2 rounded-md text-base font-medium cursor-default"
                >
                  Home
                </a>

                <a
                  href="products"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Products
                </a>

                <a
                  href="contact"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Contact
                </a>

                <a
                  href="about"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  About
                </a>

                <a
                  href="#"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Login
                </a>
              </div>
            </div>
          )}
        </Transition>
      </nav>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <div className=" rounded-lg py-20 bg-gradient-to-br from-orange-400 to-red-500">
            <div className="container mx-auto px-6">
              <h2 className="text-4xl font-bold mb-2 text-white drop-shadow-lg">
                Online Bookstore will never be this easy!
              </h2>
              <h3 className="text-2xl mb-8 text-gray-200 drop-shadow-lg">
                Get your favorite book on the go anywhere you want. Rent or Purchase available.
              </h3>

              <button className="bg-white font-bold rounded-full py-4 px-8 shadow-lg uppercase tracking-wider hover:bg-black hover:text-white">
                Our Products
              </button>
            </div>
          </div>



          <div className="container mx-auto px-6 p-10">
            <h2 className="text-4xl font-bold text-center text-gray-800 mb-8">
            Features
            </h2>
            <div className="flex items-center flex-wrap mb-20">
              <div className="w-full md:w-1/2">
                <h4 className="text-3xl text-gray-800 font-bold mb-3">Preview and Subscription</h4>
                <p className="text-gray-600 mb-8 mr-20">We are allow to read up to 50 pages before buying. You also can read online with monthly subscription rather than buying every single book.</p>
              </div>
              <div className="w-full max-w-md md:w-1/2">
                <Image src={openBook} alt="1st feature" />
              </div>
            </div>

            <div className="flex items-center flex-wrap mb-20">
              <div className=" w-full max-w-md md:w-1/2 mr-20">
                <Image src={creditCards} alt="2nd feature" />
              </div>
              <div className="w-full md:w-1/2 pl-10">
                <h4 className="text-3xl text-gray-800 font-bold mb-3">Convenient Payment System</h4>
                <p className="text-gray-600 mb-8">We accept credit/debit card payment, e-cash, mobile wallet, Paypal, Venmo, Zelle, and QR payment</p>
              </div>
            </div>

            <div className="flex items-center flex-wrap mb-20">
              <div className="w-full md:w-1/2">
                <h4 className="text-3xl text-gray-800 font-bold mb-3">Offline Reading</h4>
                <p className="text-gray-600 mb-8 mr-20">Our BookDeal website allows you to download purchased book for later read. It is available for all of your registered devices.</p>
              </div>
              <div className=" w-full max-w-md md:w-1/2">
                <Image src={offline} alt="Offline Reading" />
              </div>
            </div>
          </div>



          <div className=" bg-gradient-to-r from-orange-200 to-white rounded-lg">
            <div className="container mx-auto px-6 py-20">
              <h2 className="text-4xl font-bold text-center text-black mb-8">
                Testimonials
              </h2>
              <div className="flex flex-wrap">
                <div className="w-full md:w-1/3 px-2 mb-4">
                  <div className="bg-white rounded shadow-lg py-2">
                    <p className="text-orange-600 text-base px-6 mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    <p className="text-gray-500 text-xs md:text-sm px-6">John Doe</p>
                  </div>
                </div>
                <div className="w-full md:w-1/3 px-2 mb-4">
                  <div className="bg-white rounded shadow-lg py-2">
                    <p className="text-orange-600 text-base px-6 mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    <p className="text-gray-500 text-xs md:text-sm px-6">Jane Doe</p>
                  </div>
                </div>
                <div className="w-full md:w-1/3 px-2 mb-4">
                  <div className="bg-white rounded shadow-lg py-2">
                    <p className="text-orange-600 text-base px-6 mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    <p className="text-gray-500 text-xs md:text-sm px-6">James Doe</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </section>

        

        <section>
          <div>
            <h3 className="text-3xl pt-5">Services We Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
          <div className="md:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Creating elegant designs suited for your needs following design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">NextJS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Creating elegant designs suited for your needs following design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">NextJS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Creating elegant designs suited for your needs following design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">NextJS</p>
            </div>
          </div>
        </section>
      </main>

    </div>
  )
}
