import React, { useState } from "react";
import { Transition } from "@headlessui/react";
import Head from 'next/head'
import {FaLinkedin, FaGoogle, FaGithub, FaBars} from 'react-icons/fa';
import Image from 'next/image';
import deved from '../public/shopping-bag0.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'

import book0 from '../public/book0.jpg'
import book1 from '../public/book1.jpg'
import book2 from '../public/book2.jpg'
import book3 from '../public/book3.jpg'
import book4 from '../public/book4.jpg'
import book5 from '../public/book5.jpg'
import book6 from '../public/book6.jpg'
import book7 from '../public/book7.jpg'
import book8 from '../public/book8.jpg'
import book9 from '../public/book9.jpg'

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div>

      <Head>
        <title>BookDeal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/shopping-bag1.png" />
      </Head>

      <nav className="bg-gray-800 mb-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center">
              <div className="flex-shrink-0">
                <img
                  src='shopping-bag0.png'
                  alt="Icon"
                  className="h-10 w-10"
                />
              </div>
              <a className="text-white px-3 py-2 font-burtons text-3xl mt-3">BookDeal</a>
              <div className="hidden md:block">
                <div className="ml-10 flex items-baseline space-x-4">

                  <a
                    href="/"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Home
                  </a>

                  <a
                    href="#"
                    className=" bg-gray-700 text-white px-3 py-2 rounded-md text-sm font-medium cursor-default"
                  >
                    Products
                  </a>

                  <a
                    href="contact"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Contact
                  </a>

                  <a
                    href="about"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    About
                  </a>

                  <a
                    href="#"
                    className="text-gray-400 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                  >
                    Login
                  </a>
                </div>
              </div>

              {/*sear box*/}
              <div className="flex items-center ml-10">
                <div className="flex space-x-2">
                    <input
                        type="text"
                        className="block w-full px-4 py-2 text-black bg-white border rounded-md focus:border-orange-400 focus:ring-orange-300 focus:outline-none focus:ring focus:ring-opacity-40"
                        placeholder="Search products"
                    />
                    <button className="px-3 text-white bg-orange-600 rounded-md ">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className="w-5 h-5"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                            strokeWidth={2}
                        >
                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                            />
                        </svg>
                    </button>
                </div>
              </div>
            </div>
            <div className="-mr-2 flex md:hidden">
              <button
                onClick={() => setIsOpen(!isOpen)}
                type="button"
                className="bg-gray-900 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                aria-controls="mobile-menu"
                aria-expanded="false"
              >
                <span className="sr-only">Open main menu</span>
                {!isOpen ? (
                  <svg
                    className="block h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16"
                    />
                  </svg>
                ) : (
                  <svg
                    className="block h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </svg>
                )}
              </button>
            </div>
          </div>
        </div>

        <Transition
          show={isOpen}
          enter="transition ease-out duration-100 transform"
          enterFrom="opacity-0 scale-95"
          enterTo="opacity-100 scale-100"
          leave="transition ease-in duration-75 transform"
          leaveFrom="opacity-100 scale-100"
          leaveTo="opacity-0 scale-95"
        >
          {(ref) => (
            <div className="md:hidden" id="mobile-menu">
              <div ref={ref} className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                <a
                  href="/"
                  className="hover:bg-gray-700 text-gray-400 block px-3 py-2 rounded-md text-base font-medium"
                >
                  Home
                </a>

                <a
                  href="#"
                  className="bg-gray-700 text-white block px-3 py-2 rounded-md text-base font-medium cursor-default"
                >
                  Products
                </a>

                <a
                  href="contact"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Contact
                </a>

                <a
                  href="about"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  About
                </a>

                <a
                  href="#"
                  className="text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                >
                  Login
                </a>
              </div>
            </div>
          )}
        </Transition>
      </nav>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <div className=' text-start p-10'>
            <h2 className='text-5xl py-2 text-orange-400 drop-shadow-sm font-medium'>Our Products</h2>
            <h3 className=' text-2xl py-2'>Best books of 2022</h3>
            <p className=' text-sm py-5 leading-8'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
          
           {/* Book content */}
          <div className="flex justify-center">
            <div className="flex text-center flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book0} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">Tomorrow, and Tomorrow, and Tomorrow</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Gabrielle Zevin</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book1} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">Solito</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Javier Zamora</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book2} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">The Maid</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Nita Prose</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book3} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">I'm Glad My Mom Died</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Jennette McCurdy</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book4} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">Lessons In Chemistry</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Bonnie Garmus</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book5} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">Horse: A Novel</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Geraldine Brooks</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book6} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">The 45 Laws of Power</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Robert Greene</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book7} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">The Silent Patient</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Alex Michaelides</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book8} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">Ikigai: The Japanese Secret to a Long and Happy Life</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Héctor García</p>
              </div>
              <div className=" relative max-w-md basis-1/6 flex-1 text-center shadow-xl rounded-xl max-md hover:scale-110 hover:cursor-pointer ease-in duration-100">
                <Image src={book9} className=" absolute rounded-lg object-cover h-96 w-48" width={70} height={100} layout="responsive"/>
                <p className="text-md font-medium pt-2">The Art of God of War Ragnarök</p>
                <p className="text-sm font-medium pb-2 text-gray-500">Amy Ratcliffe </p>
              </div>
            </div>
          </div>
          
          
          {/*page button */}
          <div class="max-w-lg p-5 container flex justify-center mx-auto">
            <div class="flex flex-row mx-auto">
              <button type="button" class="bg-white text-black rounded-l-md border-r border-gray-100 py-2 hover:bg-orange-600 hover:shadow-inner hover:text-white px-3 mx-2 shadow-xl">
                <div class="flex flex-row align-middle">
                  <svg class="w-5 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path>
                  </svg>
                  <p class="ml-2">Prev</p>
                </div>
              </button>
              <button type="button" class="bg-white text-black rounded-r-md py-2 border-l border-gray-200 hover:bg-orange-600 hover:shadow-inner hover:text-white px-3 mx-2 shadow-xl">
                <div class="flex flex-row align-middle">
                  <span class="mr-2">Next</span>
                  <svg class="w-5 ml-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                  </svg>
                </div>
              </button>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services We Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
          <div className="md:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Creating elegant designs suited for your needs following design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Creating elegant designs suited for your needs following design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} alt="Services" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Creating elegant designs suited for your needs following design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>

          {/* Logo and link */}
          <div className='relative bg-gradient-to-b from-orange-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden mb-5'>
            <Image src={deved} layout='fill' objectFit='cover'/>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <FaGoogle/>
            <FaLinkedin/>
            <FaGithub/>
          </div>
        </section>
      </main>

    </div>
  )
}
